-- ============================================================
--  Datos de prueba — domótica + plantas
--  Simula 30 minutos de lecturas (1 punto cada 2 min)
--  Ejecutar en: Supabase → SQL Editor → New Query → Run
-- ============================================================

-- ── DOMÓTICA — Habitación 1 ─────────────────────────────────
INSERT INTO sensor_readings (created_at, habitacion, sensor_type, valor) VALUES
  (NOW() - INTERVAL '30 minutes', 1, 'temperatura', 24.1),
  (NOW() - INTERVAL '28 minutes', 1, 'temperatura', 24.3),
  (NOW() - INTERVAL '26 minutes', 1, 'temperatura', 24.5),
  (NOW() - INTERVAL '24 minutes', 1, 'temperatura', 24.8),
  (NOW() - INTERVAL '22 minutes', 1, 'temperatura', 25.0),
  (NOW() - INTERVAL '20 minutes', 1, 'temperatura', 25.2),
  (NOW() - INTERVAL '18 minutes', 1, 'temperatura', 25.1),
  (NOW() - INTERVAL '16 minutes', 1, 'temperatura', 24.9),
  (NOW() - INTERVAL '14 minutes', 1, 'temperatura', 24.7),
  (NOW() - INTERVAL '12 minutes', 1, 'temperatura', 24.6),
  (NOW() - INTERVAL '10 minutes', 1, 'temperatura', 24.8),
  (NOW() - INTERVAL '8 minutes',  1, 'temperatura', 25.0),
  (NOW() - INTERVAL '6 minutes',  1, 'temperatura', 25.3),
  (NOW() - INTERVAL '4 minutes',  1, 'temperatura', 25.1),
  (NOW() - INTERVAL '2 minutes',  1, 'temperatura', 24.9),

  (NOW() - INTERVAL '30 minutes', 1, 'humedad', 62.0),
  (NOW() - INTERVAL '28 minutes', 1, 'humedad', 61.5),
  (NOW() - INTERVAL '26 minutes', 1, 'humedad', 61.0),
  (NOW() - INTERVAL '24 minutes', 1, 'humedad', 60.5),
  (NOW() - INTERVAL '22 minutes', 1, 'humedad', 60.0),
  (NOW() - INTERVAL '20 minutes', 1, 'humedad', 59.5),
  (NOW() - INTERVAL '18 minutes', 1, 'humedad', 59.0),
  (NOW() - INTERVAL '16 minutes', 1, 'humedad', 59.5),
  (NOW() - INTERVAL '14 minutes', 1, 'humedad', 60.0),
  (NOW() - INTERVAL '12 minutes', 1, 'humedad', 60.5),
  (NOW() - INTERVAL '10 minutes', 1, 'humedad', 61.0),
  (NOW() - INTERVAL '8 minutes',  1, 'humedad', 61.5),
  (NOW() - INTERVAL '6 minutes',  1, 'humedad', 62.0),
  (NOW() - INTERVAL '4 minutes',  1, 'humedad', 62.5),
  (NOW() - INTERVAL '2 minutes',  1, 'humedad', 63.0),

  (NOW() - INTERVAL '30 minutes', 1, 'gas', 380),
  (NOW() - INTERVAL '28 minutes', 1, 'gas', 390),
  (NOW() - INTERVAL '26 minutes', 1, 'gas', 405),
  (NOW() - INTERVAL '24 minutes', 1, 'gas', 420),
  (NOW() - INTERVAL '22 minutes', 1, 'gas', 435),
  (NOW() - INTERVAL '20 minutes', 1, 'gas', 450),
  (NOW() - INTERVAL '18 minutes', 1, 'gas', 460),
  (NOW() - INTERVAL '16 minutes', 1, 'gas', 445),
  (NOW() - INTERVAL '14 minutes', 1, 'gas', 430),
  (NOW() - INTERVAL '12 minutes', 1, 'gas', 415),
  (NOW() - INTERVAL '10 minutes', 1, 'gas', 400),
  (NOW() - INTERVAL '8 minutes',  1, 'gas', 390),
  (NOW() - INTERVAL '6 minutes',  1, 'gas', 385),
  (NOW() - INTERVAL '4 minutes',  1, 'gas', 375),
  (NOW() - INTERVAL '2 minutes',  1, 'gas', 370),

  (NOW() - INTERVAL '30 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '28 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '26 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '24 minutes', 1, 'luz', 1),
  (NOW() - INTERVAL '22 minutes', 1, 'luz', 1),
  (NOW() - INTERVAL '20 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '18 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '16 minutes', 1, 'luz', 0),
  (NOW() - INTERVAL '14 minutes', 1, 'luz', 1),
  (NOW() - INTERVAL '12 minutes', 1, 'luz', 1),
  (NOW() - INTERVAL '10 minutes', 1, 'luz', 1),
  (NOW() - INTERVAL '8 minutes',  1, 'luz', 0),
  (NOW() - INTERVAL '6 minutes',  1, 'luz', 0),
  (NOW() - INTERVAL '4 minutes',  1, 'luz', 0),
  (NOW() - INTERVAL '2 minutes',  1, 'luz', 0);

-- ── DOMÓTICA — Habitación 2 ─────────────────────────────────
INSERT INTO sensor_readings (created_at, habitacion, sensor_type, valor) VALUES
  (NOW() - INTERVAL '30 minutes', 2, 'temperatura', 22.5),
  (NOW() - INTERVAL '28 minutes', 2, 'temperatura', 22.7),
  (NOW() - INTERVAL '26 minutes', 2, 'temperatura', 23.0),
  (NOW() - INTERVAL '24 minutes', 2, 'temperatura', 23.2),
  (NOW() - INTERVAL '22 minutes', 2, 'temperatura', 23.5),
  (NOW() - INTERVAL '20 minutes', 2, 'temperatura', 23.7),
  (NOW() - INTERVAL '18 minutes', 2, 'temperatura', 23.9),
  (NOW() - INTERVAL '16 minutes', 2, 'temperatura', 24.1),
  (NOW() - INTERVAL '14 minutes', 2, 'temperatura', 23.8),
  (NOW() - INTERVAL '12 minutes', 2, 'temperatura', 23.6),
  (NOW() - INTERVAL '10 minutes', 2, 'temperatura', 23.4),
  (NOW() - INTERVAL '8 minutes',  2, 'temperatura', 23.2),
  (NOW() - INTERVAL '6 minutes',  2, 'temperatura', 23.0),
  (NOW() - INTERVAL '4 minutes',  2, 'temperatura', 22.8),
  (NOW() - INTERVAL '2 minutes',  2, 'temperatura', 22.6),

  (NOW() - INTERVAL '30 minutes', 2, 'humedad', 68.0),
  (NOW() - INTERVAL '28 minutes', 2, 'humedad', 67.5),
  (NOW() - INTERVAL '26 minutes', 2, 'humedad', 67.0),
  (NOW() - INTERVAL '24 minutes', 2, 'humedad', 66.5),
  (NOW() - INTERVAL '22 minutes', 2, 'humedad', 66.0),
  (NOW() - INTERVAL '20 minutes', 2, 'humedad', 65.5),
  (NOW() - INTERVAL '18 minutes', 2, 'humedad', 65.0),
  (NOW() - INTERVAL '16 minutes', 2, 'humedad', 64.5),
  (NOW() - INTERVAL '14 minutes', 2, 'humedad', 64.0),
  (NOW() - INTERVAL '12 minutes', 2, 'humedad', 64.5),
  (NOW() - INTERVAL '10 minutes', 2, 'humedad', 65.0),
  (NOW() - INTERVAL '8 minutes',  2, 'humedad', 65.5),
  (NOW() - INTERVAL '6 minutes',  2, 'humedad', 66.0),
  (NOW() - INTERVAL '4 minutes',  2, 'humedad', 66.5),
  (NOW() - INTERVAL '2 minutes',  2, 'humedad', 67.0),

  (NOW() - INTERVAL '30 minutes', 2, 'gas', 290),
  (NOW() - INTERVAL '28 minutes', 2, 'gas', 295),
  (NOW() - INTERVAL '26 minutes', 2, 'gas', 300),
  (NOW() - INTERVAL '24 minutes', 2, 'gas', 310),
  (NOW() - INTERVAL '22 minutes', 2, 'gas', 320),
  (NOW() - INTERVAL '20 minutes', 2, 'gas', 315),
  (NOW() - INTERVAL '18 minutes', 2, 'gas', 308),
  (NOW() - INTERVAL '16 minutes', 2, 'gas', 302),
  (NOW() - INTERVAL '14 minutes', 2, 'gas', 298),
  (NOW() - INTERVAL '12 minutes', 2, 'gas', 292),
  (NOW() - INTERVAL '10 minutes', 2, 'gas', 288),
  (NOW() - INTERVAL '8 minutes',  2, 'gas', 285),
  (NOW() - INTERVAL '6 minutes',  2, 'gas', 282),
  (NOW() - INTERVAL '4 minutes',  2, 'gas', 280),
  (NOW() - INTERVAL '2 minutes',  2, 'gas', 278),

  (NOW() - INTERVAL '30 minutes', 2, 'luz', 1),
  (NOW() - INTERVAL '28 minutes', 2, 'luz', 1),
  (NOW() - INTERVAL '26 minutes', 2, 'luz', 1),
  (NOW() - INTERVAL '24 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '22 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '20 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '18 minutes', 2, 'luz', 1),
  (NOW() - INTERVAL '16 minutes', 2, 'luz', 1),
  (NOW() - INTERVAL '14 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '12 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '10 minutes', 2, 'luz', 0),
  (NOW() - INTERVAL '8 minutes',  2, 'luz', 1),
  (NOW() - INTERVAL '6 minutes',  2, 'luz', 1),
  (NOW() - INTERVAL '4 minutes',  2, 'luz', 1),
  (NOW() - INTERVAL '2 minutes',  2, 'luz', 0);

-- ── PLANTAS ─────────────────────────────────────────────────
-- horas_sol y horas_sombra se acumulan progresivamente (igual que millis() del ESP32)
INSERT INTO plant_readings (created_at, sensor_type, valor) VALUES
  (NOW() - INTERVAL '30 minutes', 'temperatura', 26.5),
  (NOW() - INTERVAL '28 minutes', 'temperatura', 26.8),
  (NOW() - INTERVAL '26 minutes', 'temperatura', 27.1),
  (NOW() - INTERVAL '24 minutes', 'temperatura', 27.3),
  (NOW() - INTERVAL '22 minutes', 'temperatura', 27.5),
  (NOW() - INTERVAL '20 minutes', 'temperatura', 27.8),
  (NOW() - INTERVAL '18 minutes', 'temperatura', 28.0),
  (NOW() - INTERVAL '16 minutes', 'temperatura', 28.2),
  (NOW() - INTERVAL '14 minutes', 'temperatura', 27.9),
  (NOW() - INTERVAL '12 minutes', 'temperatura', 27.6),
  (NOW() - INTERVAL '10 minutes', 'temperatura', 27.3),
  (NOW() - INTERVAL '8 minutes',  'temperatura', 27.1),
  (NOW() - INTERVAL '6 minutes',  'temperatura', 26.9),
  (NOW() - INTERVAL '4 minutes',  'temperatura', 26.7),
  (NOW() - INTERVAL '2 minutes',  'temperatura', 26.5),

  (NOW() - INTERVAL '30 minutes', 'humedad_aire', 65.0),
  (NOW() - INTERVAL '28 minutes', 'humedad_aire', 64.5),
  (NOW() - INTERVAL '26 minutes', 'humedad_aire', 64.0),
  (NOW() - INTERVAL '24 minutes', 'humedad_aire', 63.5),
  (NOW() - INTERVAL '22 minutes', 'humedad_aire', 63.0),
  (NOW() - INTERVAL '20 minutes', 'humedad_aire', 62.5),
  (NOW() - INTERVAL '18 minutes', 'humedad_aire', 62.0),
  (NOW() - INTERVAL '16 minutes', 'humedad_aire', 61.5),
  (NOW() - INTERVAL '14 minutes', 'humedad_aire', 61.0),
  (NOW() - INTERVAL '12 minutes', 'humedad_aire', 61.5),
  (NOW() - INTERVAL '10 minutes', 'humedad_aire', 62.0),
  (NOW() - INTERVAL '8 minutes',  'humedad_aire', 62.5),
  (NOW() - INTERVAL '6 minutes',  'humedad_aire', 63.0),
  (NOW() - INTERVAL '4 minutes',  'humedad_aire', 63.5),
  (NOW() - INTERVAL '2 minutes',  'humedad_aire', 64.0),

  (NOW() - INTERVAL '30 minutes', 'luz_estado', 0),
  (NOW() - INTERVAL '28 minutes', 'luz_estado', 0),
  (NOW() - INTERVAL '26 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '24 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '22 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '20 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '18 minutes', 'luz_estado', 0),
  (NOW() - INTERVAL '16 minutes', 'luz_estado', 0),
  (NOW() - INTERVAL '14 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '12 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '10 minutes', 'luz_estado', 1),
  (NOW() - INTERVAL '8 minutes',  'luz_estado', 0),
  (NOW() - INTERVAL '6 minutes',  'luz_estado', 0),
  (NOW() - INTERVAL '4 minutes',  'luz_estado', 1),
  (NOW() - INTERVAL '2 minutes',  'luz_estado', 1),

  -- humedad_suelo: valor RAW — 2800 = algo seco (~32%), 1800 = bien húmedo (~56%)
  (NOW() - INTERVAL '30 minutes', 'humedad_suelo', 2800),
  (NOW() - INTERVAL '28 minutes', 'humedad_suelo', 2780),
  (NOW() - INTERVAL '26 minutes', 'humedad_suelo', 2750),
  (NOW() - INTERVAL '24 minutes', 'humedad_suelo', 2720),
  (NOW() - INTERVAL '22 minutes', 'humedad_suelo', 2690),
  (NOW() - INTERVAL '20 minutes', 'humedad_suelo', 2650),
  (NOW() - INTERVAL '18 minutes', 'humedad_suelo', 2600),
  (NOW() - INTERVAL '16 minutes', 'humedad_suelo', 2550),
  (NOW() - INTERVAL '14 minutes', 'humedad_suelo', 2500),
  (NOW() - INTERVAL '12 minutes', 'humedad_suelo', 2460),
  (NOW() - INTERVAL '10 minutes', 'humedad_suelo', 2420),
  (NOW() - INTERVAL '8 minutes',  'humedad_suelo', 2380),
  (NOW() - INTERVAL '6 minutes',  'humedad_suelo', 2340),
  (NOW() - INTERVAL '4 minutes',  'humedad_suelo', 2300),
  (NOW() - INTERVAL '2 minutes',  'humedad_suelo', 2260),

  -- horas_sol: acumulando desde 0 (el ESP32 arrancó hace 30 min, aprox 8 min con luz)
  (NOW() - INTERVAL '30 minutes', 'horas_sol', 0.0000),
  (NOW() - INTERVAL '28 minutes', 'horas_sol', 0.0000),
  (NOW() - INTERVAL '26 minutes', 'horas_sol', 0.0333),
  (NOW() - INTERVAL '24 minutes', 'horas_sol', 0.0667),
  (NOW() - INTERVAL '22 minutes', 'horas_sol', 0.1000),
  (NOW() - INTERVAL '20 minutes', 'horas_sol', 0.1333),
  (NOW() - INTERVAL '18 minutes', 'horas_sol', 0.1333),
  (NOW() - INTERVAL '16 minutes', 'horas_sol', 0.1333),
  (NOW() - INTERVAL '14 minutes', 'horas_sol', 0.1667),
  (NOW() - INTERVAL '12 minutes', 'horas_sol', 0.2000),
  (NOW() - INTERVAL '10 minutes', 'horas_sol', 0.2333),
  (NOW() - INTERVAL '8 minutes',  'horas_sol', 0.2333),
  (NOW() - INTERVAL '6 minutes',  'horas_sol', 0.2333),
  (NOW() - INTERVAL '4 minutes',  'horas_sol', 0.2667),
  (NOW() - INTERVAL '2 minutes',  'horas_sol', 0.3000),

  -- horas_sombra: los minutos sin luz
  (NOW() - INTERVAL '30 minutes', 'horas_sombra', 0.0000),
  (NOW() - INTERVAL '28 minutes', 'horas_sombra', 0.0333),
  (NOW() - INTERVAL '26 minutes', 'horas_sombra', 0.0333),
  (NOW() - INTERVAL '24 minutes', 'horas_sombra', 0.0333),
  (NOW() - INTERVAL '22 minutes', 'horas_sombra', 0.0333),
  (NOW() - INTERVAL '20 minutes', 'horas_sombra', 0.0333),
  (NOW() - INTERVAL '18 minutes', 'horas_sombra', 0.0667),
  (NOW() - INTERVAL '16 minutes', 'horas_sombra', 0.1000),
  (NOW() - INTERVAL '14 minutes', 'horas_sombra', 0.1000),
  (NOW() - INTERVAL '12 minutes', 'horas_sombra', 0.1000),
  (NOW() - INTERVAL '10 minutes', 'horas_sombra', 0.1000),
  (NOW() - INTERVAL '8 minutes',  'horas_sombra', 0.1333),
  (NOW() - INTERVAL '6 minutes',  'horas_sombra', 0.1667),
  (NOW() - INTERVAL '4 minutes',  'horas_sombra', 0.1667),
  (NOW() - INTERVAL '2 minutes',  'horas_sombra', 0.1667);

-- ── Verificar resultados ─────────────────────────────────────
SELECT 'sensor_readings' AS tabla, COUNT(*) FROM sensor_readings
UNION ALL
SELECT 'plant_readings',           COUNT(*) FROM plant_readings;
